const fs = require('fs');
const code = fs.readFileSync('data.js', 'utf8');
const existing = [];
const regex = /\{ name: "([^"]+)", tier: (\d) \}/g;
let m;
while ((m = regex.exec(code)) !== null) existing.push(m[1].toLowerCase());

const newColleges = [
  { name: "Acharya Institute of Technology Bangalore", tier: 3 },
  { name: "Acharya and BM Reddy College of Engineering Bangalore", tier: 3 },
  { name: "Adichunchanagiri School of Engineering Bangalore", tier: 3 },
  { name: "Akshaya Institute of Technology Bangalore", tier: 3 },
  { name: "Alpha College of Engineering Bangalore", tier: 3 },
  { name: "Amruta Institute of Engineering and Management Sciences Bangalore", tier: 3 },
  { name: "Anekal College of Engineering Bangalore", tier: 3 },
  { name: "Anjuman Institute of Technology Bangalore", tier: 3 },
  { name: "Atria College of Engineering Bangalore", tier: 3 },
  { name: "Aziz Sait Institute of Engineering and Technology Bangalore", tier: 3 },
  { name: "Bangalore College of Engineering and Technology Bangalore", tier: 3 },
  { name: "Bangalore Institute of Technology Bangalore", tier: 3 },
  { name: "Bangalore Technological Institute Bangalore", tier: 3 },
  { name: "Bharath Institute of Engineering Bangalore", tier: 3 },
  { name: "Bhoomi College of Engineering Bangalore", tier: 3 },
  { name: "Bhuvaneshwari College of Engineering Bangalore", tier: 3 },
  { name: "Canara College of Engineering Bangalore", tier: 3 },
  { name: "Capital Institute of Technology Bangalore", tier: 3 },
  { name: "Cauvery Institute of Technology Bangalore", tier: 3 },
  { name: "Channabasaveshwara Institute of Technology Bangalore", tier: 3 },
  { name: "Christ College of Engineering Bangalore", tier: 3 },
  { name: "CMR College of Engineering and Technology Bangalore", tier: 3 },
  { name: "CMR University Bangalore", tier: 3 },
  { name: "Dayananda Sagar University Bangalore", tier: 3 },
  { name: "Deccan College of Engineering Bangalore", tier: 3 },
  { name: "Divya Jyothi College of Engineering Bangalore", tier: 3 },
  { name: "Dr CNS Institute of Technology Bangalore", tier: 3 },
  { name: "Dr Kariappa College of Engineering Bangalore", tier: 3 },
  { name: "East West College of Engineering Bangalore", tier: 3 },
  { name: "Ekalavya Institute of Technology Bangalore", tier: 3 },
  { name: "Francis Xavier Engineering College Bangalore", tier: 3 },
  { name: "Ganga Institute of Technology Bangalore", tier: 3 },
  { name: "Global Institute of Engineering Bangalore", tier: 3 },
  { name: "Gopalan Institute of Technology Bangalore", tier: 3 },
  { name: "Grace College of Engineering Bangalore", tier: 3 },
  { name: "Guru Nanak Institute of Technology Bangalore", tier: 3 },
  { name: "Hillside College of Engineering Bangalore", tier: 3 },
  { name: "Hindustan Institute of Engineering Technology Bangalore", tier: 3 },
  { name: "Indira Gandhi Memorial Institute of Technology Bangalore", tier: 3 },
  { name: "Indus College of Engineering Bangalore", tier: 3 },
  { name: "Innovative Institute of Technology Bangalore", tier: 3 },
  { name: "International Institute of Engineering Bangalore", tier: 3 },
  { name: "Jain Institute of Technology Bangalore", tier: 3 },
  { name: "Janatha Shikshana Samithi Institute of Technology Bangalore", tier: 3 },
  { name: "Jawaharlal Nehru College of Engineering Bangalore", tier: 3 },
  { name: "Jnana Bharathi Institute of Technology Bangalore", tier: 3 },
  { name: "Jnana Ganga Institute of Technology Bangalore", tier: 3 },
  { name: "Jnana Jyothi Institute of Technology Bangalore", tier: 3 },
  { name: "Jnana Sindhu Institute of Technology Bangalore", tier: 3 },
  { name: "Jnana Yoga Institute of Technology Bangalore", tier: 3 },
  { name: "Kalyani Institute of Technology Bangalore", tier: 3 },
  { name: "Kengeri Institute of Technology Bangalore", tier: 3 },
  { name: "KNS Institute of Technology Bangalore", tier: 3 },
  { name: "Kumaran Institute of Technology Bangalore", tier: 3 },
  { name: "Lal Bahadur Shastri Institute of Technology Bangalore", tier: 3 },
  { name: "Lingarajappa College of Engineering Bangalore", tier: 3 },
  { name: "Lotus Institute of Engineering Bangalore", tier: 3 },
  { name: "Mahatma Gandhi Institute of Technology Bangalore", tier: 3 },
  { name: "Malnad Institute of Technology Bangalore", tier: 3 },
  { name: "Mangala Institute of Technology Bangalore", tier: 3 },
  { name: "Matha Institute of Technology Bangalore", tier: 3 },
  { name: "Mount Carmel College Bangalore", tier: 3 },
  { name: "Mysore Institute of Technology Bangalore", tier: 3 },
  { name: "Nandi Institute of Technology Bangalore", tier: 3 },
  { name: "National Institute of Engineering Bangalore", tier: 3 },
  { name: "Navkis College of Engineering Bangalore", tier: 3 },
  { name: "Nehru Institute of Engineering Bangalore", tier: 3 },
  { name: "Nrupathunga University Bangalore", tier: 3 },
  { name: "Padmashree Institute of Management Bangalore", tier: 3 },
  { name: "Poornaprajna College of Engineering Bangalore", tier: 3 },
  { name: "Prajwal College of Engineering Bangalore", tier: 3 },
  { name: "Raja Rajeshwari Medical College Bangalore", tier: 3 },
  { name: "Rajiv Gandhi Institute of Technology Bangalore", tier: 3 },
  { name: "Ramaiah University of Applied Sciences Bangalore", tier: 3 },
  { name: "Rooman Technologies Bangalore", tier: 3 },
  { name: "Sarada Vilas College of Engineering Bangalore", tier: 3 },
  { name: "Saraswathi Institute of Technology Bangalore", tier: 3 },
  { name: "Sardar Patel Institute of Technology Bangalore", tier: 3 },
  { name: "Seshadripuram Institute of Management Studies Bangalore", tier: 3 },
  { name: "Shri Dharmasthala Manjunatheshwara College Bangalore", tier: 3 },
  { name: "Siddaganga Institute of Technology Bangalore", tier: 3 },
  { name: "Srinivasa Institute of Technology Bangalore", tier: 3 },
  { name: "St Francis De Sales College Bangalore", tier: 3 },
  { name: "St Joseph College of Engineering Bangalore", tier: 3 },
  { name: "St Peters Engineering College Bangalore", tier: 3 },
  { name: "Swamy Vivekananda Engineering College Bangalore", tier: 3 },
  { name: "Symbiosis Institute of Technology Bangalore", tier: 3 },
  { name: "Tatyasaheb Kore Institute of Engineering Bangalore", tier: 3 },
  { name: "Tontadarya College of Engineering Bangalore", tier: 3 },
  { name: "Tumkur Institute of Technology Bangalore", tier: 3 },
  { name: "Vidyavardhaka College of Engineering Bangalore", tier: 3 },
  { name: "Vivekananda College of Engineering Bangalore", tier: 3 },
  { name: "Welingkar Institute of Management Bangalore", tier: 3 },
  { name: "Yellamma Dasappa Institute of Technology Bangalore", tier: 3 },
  { name: "Presidency Institute of Engineering Bangalore", tier: 3 },
  { name: "Sri Siddhartha Institute of Technology Bangalore", tier: 3 },
  { name: "Sindhi Institute of Management Bangalore", tier: 3 },
  { name: "Bangalore North University Bangalore", tier: 3 },
  { name: "BMS Evening College of Engineering Bangalore", tier: 3 },
  { name: "Eklavya College of Engineering Bangalore", tier: 3 },
];

const toAdd = newColleges.filter(c => !existing.includes(c.name.toLowerCase()));
console.log('New colleges to add:', toAdd.length);

const insertPoint = code.indexOf('];\n\nconst tierInfo');
const newLines = toAdd.map(c => `  { name: "${c.name}", tier: ${c.tier} },`).join('\n');
const updated = code.slice(0, insertPoint) + '\n' + newLines + '\n' + code.slice(insertPoint);
fs.writeFileSync('data.js', updated, 'utf8');
console.log('Done! Total now:', 821 + toAdd.length);
