window.colleges = [
  { name: "IIT Madras", tier: 1 },
  { name: "IIT Delhi", tier: 1 },
  { name: "IIT Bombay", tier: 1 },
  { name: "IIT Kanpur", tier: 1 },
  { name: "IIT Kharagpur", tier: 1 },
  { name: "IIT Roorkee", tier: 1 },
  { name: "IIT Hyderabad", tier: 1 },
  { name: "IIT Guwahati", tier: 1 },
  { name: "NIT Trichy", tier: 1 },
  { name: "IIT BHU Varanasi", tier: 1 },
  { name: "IIT Varanasi (IIT BHU)", tier: 1 },
  { name: "BITS Pilani", tier: 1 },
  { name: "IIT Indore", tier: 1 },
  { name: "NIT Rourkela", tier: 1 },
  { name: "SRM Institute of Science and Technology", tier: 1 },
  { name: "SRM University Chennai", tier: 1 },
  { name: "VIT Vellore", tier: 1 },
  { name: "NIT Surathkal", tier: 1 },
  { name: "Jadavpur University", tier: 1 },
  { name: "IIT Patna", tier: 1 },
  { name: "Anna University", tier: 1 },
  { name: "NIT Calicut", tier: 1 },
  { name: "Siksha O Anusandhan University", tier: 1 },
  { name: "Amrita Vishwa Vidyapeetham", tier: 1 },
  { name: "Jamia Millia Islamia", tier: 1 },
  { name: "IIT Gandhinagar", tier: 1 },
  { name: "IIT Mandi", tier: 1 },
  { name: "IIT Jodhpur", tier: 1 },
  { name: "NIT Warangal", tier: 1 },
  { name: "Thapar Institute of Engineering", tier: 1 },
  { name: "Delhi Technological University", tier: 1 },
  { name: "Chandigarh University", tier: 1 },
  { name: "IIT Ropar", tier: 1 },
  { name: "Kalasalingam Academy of Research", tier: 1 },
  { name: "Aligarh Muslim University", tier: 1 },
  { name: "KL University", tier: 1 },
  { name: "KIIT University", tier: 1 },
  { name: "Amity University Noida", tier: 1 },
  { name: "IIIT Hyderabad", tier: 1 },
  { name: "IIT Bhubaneswar", tier: 1 },
  { name: "SASTRA University", tier: 1 },
  { name: "Institute of Chemical Technology Mumbai", tier: 1 },
  { name: "Malaviya NIT Jaipur", tier: 1 },
  { name: "Visvesvaraya NIT Nagpur", tier: 1 },
  { name: "Saveetha Institute of Medical and Technical Sciences", tier: 1 },
  { name: "Symbiosis International University", tier: 1 },
  { name: "Sri Sivasubramaniya Nadar College of Engineering", tier: 1 },
  { name: "Lovely Professional University", tier: 1 },
  { name: "NIT Durgapur", tier: 1 },
  { name: "NIT Silchar", tier: 1 },
  { name: "Birla Institute of Technology Mesra", tier: 2 },
  { name: "Graphic Era University", tier: 2 },
  { name: "NIT Patna", tier: 2 },
  { name: "IIEST Shibpur", tier: 2 },
  { name: "NIT Jalandhar", tier: 2 },
  { name: "IIT Jammu", tier: 2 },
  { name: "IIT Tirupati", tier: 2 },
  { name: "Manipal University Jaipur", tier: 2 },
  { name: "Manipal Institute of Technology", tier: 2 },
  { name: "Madan Mohan Malaviya University of Technology", tier: 2 },
  { name: "Indian Institute of Space Science and Technology", tier: 2 },
  { name: "Motilal Nehru NIT Allahabad", tier: 2 },
  { name: "Indraprastha Institute of Information Technology", tier: 2 },
  { name: "IIT Palakkad", tier: 2 },
  { name: "NIT Delhi", tier: 2 },
  { name: "Sardar Vallabhbhai NIT Surat", tier: 2 },
  { name: "PSG College of Technology", tier: 2 },
  { name: "Sathyabama Institute of Science and Technology", tier: 2 },
  { name: "IIIT Bangalore", tier: 2 },
  { name: "Netaji Subhas University of Technology", tier: 2 },
  { name: "Banasthali Vidyapith", tier: 2 },
  { name: "IIT Bhilai", tier: 2 },
  { name: "NIT Srinagar", tier: 2 },
  { name: "University of Hyderabad", tier: 2 },
  { name: "M S Ramaiah Institute of Technology", tier: 2 },
  { name: "Christ University Bangalore", tier: 2 },
  { name: "IIT Dharwad", tier: 2 },
  { name: "Rajiv Gandhi Institute of Petroleum Technology", tier: 2 },
  { name: "Sant Longowal Institute of Engineering", tier: 2 },
  { name: "Vignan University", tier: 2 },
  { name: "Maulana Azad NIT Bhopal", tier: 2 },
  { name: "NIT Jamshedpur", tier: 2 },
  { name: "NIT Meghalaya", tier: 2 },
  { name: "Jain University Bangalore", tier: 2 },
  { name: "NIT Kurukshetra", tier: 2 },
  { name: "NIT Raipur", tier: 2 },
  { name: "Vel Tech University", tier: 2 },
  { name: "Andhra University College of Engineering", tier: 2 },
  { name: "Chitkara University Punjab", tier: 2 },
  { name: "COEP Technological University Pune", tier: 2 },
  { name: "SR University Warangal", tier: 2 },
  { name: "Defence Institute of Advanced Technology", tier: 2 },
  { name: "Panjab University", tier: 2 },
  { name: "JNTU Hyderabad", tier: 2 },
  { name: "CV Raman Global University", tier: 2 },
  { name: "IIIT Gwalior", tier: 2 },
  { name: "NIT Hamirpur", tier: 2 },
  { name: "Pandit Deendayal Energy University", tier: 2 },
  { name: "NIT Puducherry", tier: 2 },
  { name: "Sri Krishna College of Engineering and Technology", tier: 2 },
  { name: "RV College of Engineering", tier: 2 },
  { name: "Siddaganga Institute of Technology", tier: 2 },
  { name: "BMS College of Engineering", tier: 2 },
  { name: "PES University Bangalore", tier: 2 },
  { name: "DAIICT Gandhinagar", tier: 2 },
  { name: "Shiv Nadar University", tier: 2 },
  { name: "Dhirubhai Ambani Institute of ICT", tier: 2 },
  { name: "IISc Bangalore", tier: 2 },
  { name: "BITS Goa", tier: 2 },
  { name: "BITS Hyderabad", tier: 2 },
  { name: "NIT Agartala", tier: 2 },
  { name: "NIT Manipur", tier: 2 },
  { name: "NIT Mizoram", tier: 2 },
  { name: "NIT Sikkim", tier: 2 },
  { name: "NIT Uttarakhand", tier: 2 },
  { name: "NIT Arunachal Pradesh", tier: 2 },
  { name: "NIT Andhra Pradesh", tier: 2 },
  { name: "NIT Goa", tier: 2 },
  { name: "IIIT Delhi", tier: 2 },
  { name: "IIIT Allahabad", tier: 2 },
  { name: "IIIT Pune", tier: 2 },
  { name: "IIIT Jabalpur", tier: 2 },
  { name: "IIIT Kancheepuram", tier: 2 },
  { name: "IIIT Lucknow", tier: 2 },
  { name: "IIIT Vadodara", tier: 2 },
  { name: "IIIT Ranchi", tier: 2 },
  { name: "IIIT Nagpur", tier: 2 },
  { name: "IIIT Bhopal", tier: 2 },
  { name: "IIIT Surat", tier: 2 },
  { name: "IIIT Kalyani", tier: 2 },
  { name: "IIIT Kota", tier: 2 },
  { name: "IIIT Una", tier: 2 },
  { name: "IIIT Sri City", tier: 2 },
  { name: "IIIT Naya Raipur", tier: 2 },
  { name: "UPES Dehradun", tier: 2 },
  { name: "Guru Gobind Singh Indraprastha University", tier: 2 },
  { name: "Shoolini University", tier: 2 },
  { name: "Kongu Engineering College", tier: 2 },
  { name: "SSN College of Engineering", tier: 2 },
  { name: "Thiagarajar College of Engineering", tier: 2 },
  { name: "Kumaraguru College of Technology", tier: 2 },
  { name: "Coimbatore Institute of Technology", tier: 2 },
  { name: "Bannari Amman Institute of Technology", tier: 2 },
  { name: "Rajalakshmi Engineering College", tier: 2 },
  { name: "Sri Venkateswara College of Engineering", tier: 2 },
  { name: "Mepco Schlenk Engineering College", tier: 2 },
  { name: "Velammal Engineering College", tier: 2 },
  { name: "Hindustan Institute of Technology and Science", tier: 2 },
  { name: "College of Engineering Pune", tier: 2 },
  { name: "Vishwakarma Institute of Technology", tier: 2 },
  { name: "MIT College of Engineering Pune", tier: 2 },
  { name: "Pune Institute of Computer Technology", tier: 2 },
  { name: "Walchand College of Engineering", tier: 2 },
  { name: "SPIT Mumbai", tier: 2 },
  { name: "DJ Sanghvi College of Engineering", tier: 2 },
  { name: "KJ Somaiya College of Engineering", tier: 2 },
  { name: "Vasavi College of Engineering", tier: 2 },
  { name: "Chaitanya Bharathi Institute of Technology", tier: 2 },
  { name: "Gokaraju Rangaraju Institute of Engineering", tier: 2 },
  { name: "Heritage Institute of Technology Kolkata", tier: 2 },
  { name: "College of Engineering Trivandrum", tier: 2 },
  { name: "Model Engineering College Kochi", tier: 2 },
  { name: "Cochin University of Science and Technology", tier: 2 },
  { name: "Rajagiri School of Engineering", tier: 2 },
  { name: "Punjab Engineering College", tier: 2 },
  { name: "Harcourt Butler Technical University", tier: 2 },
  { name: "Jaypee Institute of Information Technology", tier: 2 },
  { name: "Bennett University", tier: 2 },
  { name: "Galgotias University", tier: 2 },
  { name: "Nirma University Ahmedabad", tier: 2 },
  { name: "LD College of Engineering", tier: 2 },
  { name: "Dharmsinh Desai University", tier: 2 },
  { name: "Ahmedabad University", tier: 2 },
  { name: "PDPU Gandhinagar", tier: 2 },
  { name: "Sardar Patel College of Engineering", tier: 2 },
  { name: "Veermata Jijabai Technological Institute", tier: 2 },
  { name: "College of Engineering Guindy", tier: 2 },
  { name: "PEC Chandigarh", tier: 2 },
  { name: "BIT Mesra Ranchi", tier: 2 },
  { name: "Visvesvaraya Technological University", tier: 2 },
  { name: "IIT ISM Dhanbad", tier: 1 },
  { name: "DTU Delhi", tier: 2 },
  { name: "NSIT Delhi", tier: 2 },
  { name: "Ramaiah Institute of Technology Bangalore", tier: 2 },
  { name: "Easwari Engineering College", tier: 2 },
  { name: "CVR College of Engineering", tier: 2 },
  { name: "Institute of Engineering and Management Kolkata", tier: 2 },
  { name: "Techno India University", tier: 2 },
  { name: "TKM College of Engineering", tier: 2 },
  { name: "Thadomal Shahani Engineering College", tier: 2 },
  { name: "Charotar University of Science and Technology", tier: 2 },
  { name: "M. S. Engineering College", tier: 3 },
  { name: "MS Engineering College Bangalore", tier: 3 },
  { name: "Dayananda Sagar College of Engineering", tier: 3 },
  { name: "New Horizon College of Engineering", tier: 3 },
  { name: "Bangalore Institute of Technology", tier: 3 },
  { name: "Sir M Visvesvaraya Institute of Technology", tier: 3 },
  { name: "East West Institute of Technology", tier: 3 },
  { name: "Reva University", tier: 3 },
  { name: "CMR Institute of Technology", tier: 3 },
  { name: "Global Academy of Technology", tier: 3 },
  { name: "Nitte Meenakshi Institute of Technology", tier: 3 },
  { name: "KLE Technological University", tier: 3 },
  { name: "Presidency University Bangalore", tier: 3 },
  { name: "Acharya Institute of Technology", tier: 3 },
  { name: "Alliance University Bangalore", tier: 3 },
  { name: "Atria Institute of Technology", tier: 3 },
  { name: "Cambridge Institute of Technology Bangalore", tier: 3 },
  { name: "Don Bosco Institute of Technology Bangalore", tier: 3 },
  { name: "Gopalan College of Engineering", tier: 3 },
  { name: "HKBK College of Engineering", tier: 3 },
  { name: "Impact College of Engineering", tier: 3 },
  { name: "Jyothy Institute of Technology", tier: 3 },
  { name: "Kammavari Sangham Institute of Technology", tier: 3 },
  { name: "Nagarjuna College of Engineering", tier: 3 },
  { name: "Sapthagiri College of Engineering Bangalore", tier: 3 },
  { name: "Brindavan College of Engineering Bangalore", tier: 3 },
  { name: "Rajarajeswari College of Engineering Bangalore", tier: 3 },
  { name: "City Engineering College Bangalore", tier: 3 },
  { name: "Vemana Institute of Technology Bangalore", tier: 3 },
  { name: "Yellamma Dasappa Institute of Technology Bangalore", tier: 3 },
  { name: "Sri Krishna Institute of Technology Bangalore", tier: 3 },
  { name: "RNS Institute of Technology Bangalore", tier: 3 },
  { name: "RR Institute of Technology Bangalore", tier: 3 },
  { name: "MVJ College of Engineering Bangalore", tier: 3 },
  { name: "BMS Institute of Technology Bangalore", tier: 3 },
  { name: "Srinidhi Institute of Science and Technology Bangalore", tier: 3 },
  { name: "East Point College of Engineering Bangalore", tier: 3 },
  { name: "Sambhram Institute of Technology Bangalore", tier: 3 },
  { name: "T John Institute of Technology Bangalore", tier: 3 },
  { name: "Oxford College of Engineering Bangalore", tier: 3 },
  { name: "Garden City University Bangalore", tier: 3 },
  { name: "Sai Vidya Institute of Technology Bangalore", tier: 3 },
  { name: "Sri Sairam College of Engineering Bangalore", tier: 3 },
  { name: "Soundarya Institute of Management and Science Bangalore", tier: 3 },
  { name: "KS Institute of Technology Bangalore", tier: 3 },
  { name: "Dr Ambedkar Institute of Technology Bangalore", tier: 3 },
  { name: "Loka Shikshana Trust College of Engineering Bangalore", tier: 3 },
  { name: "Visvesvaraya College of Engineering Bangalore", tier: 3 },
  { name: "Vivekananda Institute of Technology Bangalore", tier: 3 },
  { name: "AMC Engineering College Bangalore", tier: 3 },
  { name: "Bangalore Technological Institute", tier: 3 },
  { name: "Channabasaveshwara Institute of Technology Gubbi", tier: 3 },
  { name: "Ghousia College of Engineering Ramanagara", tier: 3 },
  { name: "Sahyadri College of Engineering Mangalore", tier: 3 },
  { name: "Srinivas Institute of Technology Mangalore", tier: 3 },
  { name: "Canara Engineering College Mangalore", tier: 3 },
  { name: "St Joseph Engineering College Mangalore", tier: 3 },
  { name: "Yenepoya Institute of Technology Mangalore", tier: 3 },
  { name: "Bearys Institute of Technology Mangalore", tier: 3 },
  { name: "Nitte Institute of Technology Mangalore", tier: 3 },
  { name: "NMAM Institute of Technology Nitte", tier: 3 },
  { name: "Alva's Institute of Engineering Moodbidri", tier: 3 },
  { name: "KVG College of Engineering Sullia", tier: 3 },
  { name: "Karavali Institute of Technology Mangalore", tier: 3 },
  { name: "Mangalore Institute of Technology and Engineering", tier: 3 },
  { name: "Shri Madhwa Vadiraja Institute of Technology Bantwal", tier: 3 },
  { name: "PA College of Engineering Mangalore", tier: 3 },
  { name: "KLS Gogte Institute of Technology Belgaum", tier: 3 },
  { name: "KLE College of Engineering and Technology Belgaum", tier: 3 },
  { name: "Basaveshwar Engineering College Bagalkot", tier: 3 },
  { name: "Maratha Mandal Engineering College Belgaum", tier: 3 },
  { name: "SDM College of Engineering Dharwad", tier: 3 },
  { name: "BVB College of Engineering Hubli", tier: 3 },
  { name: "Angadi Institute of Technology Belgaum", tier: 3 },
  { name: "Bapuji Institute of Engineering and Technology Davangere", tier: 3 },
  { name: "GM Institute of Technology Davangere", tier: 3 },
  { name: "JSS Science and Technology University Mysore", tier: 3 },
  { name: "NIE Institute of Technology Mysore", tier: 3 },
  { name: "Vidyavardhaka College of Engineering Mysore", tier: 3 },
  { name: "Maharaja Institute of Technology Mysore", tier: 3 },
  { name: "Sri Jayachamarajendra College of Engineering Mysore", tier: 3 },
  { name: "Farooqia College of Engineering Mysore", tier: 3 },
  { name: "Malnad College of Engineering Hassan", tier: 3 },
  { name: "Adichunchanagiri Institute of Technology Chikmagalur", tier: 3 },
  { name: "Jawaharlal Nehru National College of Engineering Shimoga", tier: 3 },
  { name: "Siddaganga Institute of Technology Tumkur", tier: 3 },
  { name: "Sri Siddhartha Institute of Technology Tumkur", tier: 3 },
  { name: "Shridevi Institute of Engineering Tumkur", tier: 3 },
  { name: "Kalpataru Institute of Technology Tiptur", tier: 3 },
  { name: "S J C Institute of Technology Chickballapur", tier: 3 },
  { name: "Kolar Institute of Technology", tier: 3 },
  { name: "Ballari Institute of Technology and Management", tier: 3 },
  { name: "Vijayanagara Sri Krishnadevaraya University Bellary", tier: 3 },
  { name: "Navodaya Institute of Technology Raichur", tier: 3 },
  { name: "PDA College of Engineering Kalaburagi", tier: 3 },
  { name: "Poojya Doddappa Appa College of Engineering Kalaburagi", tier: 3 },
  { name: "Guru Nanak Dev Engineering College Bidar", tier: 3 },
  { name: "Lingaraj Appa Engineering College Bidar", tier: 3 },
  { name: "Hirasugar Institute of Technology Nidasoshi", tier: 3 },
  { name: "Tontadarya College of Engineering Gadag", tier: 3 },
  { name: "Rural Engineering College Hulkoti", tier: 3 },
  { name: "Government Engineering College Hassan", tier: 3 },
  { name: "Government Engineering College Mysore", tier: 3 },
  { name: "Government Engineering College Bangalore", tier: 3 },
  { name: "Government Engineering College Ramanagara", tier: 3 },
  { name: "Government Engineering College Mandya", tier: 3 },
  { name: "Government Engineering College Kolar", tier: 3 },
  { name: "Government Engineering College Chickballapur", tier: 3 },
  { name: "Government Engineering College Raichur", tier: 3 },
  { name: "Government Engineering College Bidar", tier: 3 },
  { name: "Government Engineering College Dharwad", tier: 3 },
  { name: "Government Engineering College Bagalkot", tier: 3 },
  { name: "Government Engineering College Haveri", tier: 3 },
  { name: "Government Engineering College Koppal", tier: 3 },
  { name: "Government Engineering College Karwar", tier: 3 },
  { name: "Government Engineering College Gadag", tier: 3 },
  { name: "Government Engineering College Yadgir", tier: 3 },
  { name: "Government Engineering College Vijayanagara", tier: 3 },
  { name: "Government Engineering College Gangavathi", tier: 3 },
  { name: "Government Engineering College Sindhanur", tier: 3 },
  { name: "Government Engineering College Chamarajanagar", tier: 3 },
  { name: "Government Engineering College Chikkamagaluru", tier: 3 },
  { name: "Government Engineering College Holalkere", tier: 3 },
  { name: "Government Engineering College Bhadravathi", tier: 3 },
  { name: "Government Engineering College Bidadi", tier: 3 },
  { name: "Government Engineering College Kushalnagar", tier: 3 },
  { name: "Government Engineering College Krishnarajapete", tier: 3 },
  { name: "Government Engineering College Hanagal", tier: 3 },
  { name: "Government Engineering College Belur", tier: 3 },
  { name: "Government Engineering College Uttara Kannada", tier: 3 },
  { name: "Cummins College of Engineering", tier: 3 },
  { name: "Atharva College of Engineering", tier: 3 },
  { name: "Terna Engineering College", tier: 3 },
  { name: "MGM College of Engineering Nanded", tier: 3 },
  { name: "Shri Ramdeobaba College of Engineering", tier: 3 },
  { name: "Yeshwantrao Chavan College of Engineering", tier: 3 },
  { name: "G.H. Raisoni College of Engineering", tier: 3 },
  { name: "Sinhgad College of Engineering Pune", tier: 3 },
  { name: "Pimpri Chinchwad College of Engineering", tier: 3 },
  { name: "Bharati Vidyapeeth College of Engineering Pune", tier: 3 },
  { name: "Sandip Institute of Technology Nashik", tier: 3 },
  { name: "Jawaharlal Nehru Engineering College Aurangabad", tier: 3 },
  { name: "Annamalai University", tier: 3 },
  { name: "Bharathiar University", tier: 3 },
  { name: "Bharathidasan University", tier: 3 },
  { name: "Madurai Kamaraj University", tier: 3 },
  { name: "Karpagam Academy of Higher Education", tier: 3 },
  { name: "Sri Ramakrishna Engineering College", tier: 3 },
  { name: "Amrita School of Engineering Coimbatore", tier: 3 },
  { name: "Panimalar Engineering College", tier: 3 },
  { name: "Jeppiaar Engineering College", tier: 3 },
  { name: "SRM Valliammai Engineering College", tier: 3 },
  { name: "JNTU Kakinada", tier: 3 },
  { name: "JNTU Anantapur", tier: 3 },
  { name: "Sri Venkateswara University", tier: 3 },
  { name: "Gayatri Vidya Parishad College of Engineering", tier: 3 },
  { name: "Anil Neerukonda Institute of Technology", tier: 3 },
  { name: "Raghu Engineering College", tier: 3 },
  { name: "Maharaja Agrasen Institute of Technology", tier: 3 },
  { name: "Bhagwan Parshuram Institute of Technology", tier: 3 },
  { name: "Amity University Gurugram", tier: 3 },
  { name: "GL Bajaj Institute of Technology", tier: 3 },
  { name: "Noida Institute of Engineering and Technology", tier: 3 },
  { name: "Bundelkhand Institute of Engineering and Technology", tier: 3 },
  { name: "Shri Ramswaroop Memorial College", tier: 3 },
  { name: "Jaypee University of Engineering and Technology", tier: 3 },
  { name: "Lakshmi Narain College of Technology", tier: 3 },
  { name: "Sage University Bhopal", tier: 3 },
  { name: "Rungta College of Engineering Bhilai", tier: 3 },
  { name: "Bhilai Institute of Technology", tier: 3 },
  { name: "Poornima College of Engineering", tier: 3 },
  { name: "Arya College of Engineering", tier: 3 },
  { name: "Jaipur Engineering College", tier: 3 },
  { name: "JECRC University Jaipur", tier: 3 },
  { name: "Vivekananda Global University", tier: 3 },
  { name: "Marwadi University Rajkot", tier: 3 },
  { name: "Parul University Vadodara", tier: 3 },
  { name: "Ganpat University Mehsana", tier: 3 },
  { name: "Sal Engineering and Technical Institute", tier: 3 },
  { name: "Narula Institute of Technology", tier: 3 },
  { name: "Meghnad Saha Institute of Technology", tier: 3 },
  { name: "Haldia Institute of Technology", tier: 3 },
  { name: "Kalyani Government Engineering College", tier: 3 },
  { name: "JIS College of Engineering", tier: 3 },
  { name: "Government Engineering College Thrissur", tier: 3 },
  { name: "Mar Athanasius College of Engineering", tier: 3 },
  { name: "Sree Buddha College of Engineering", tier: 3 },
  { name: "Marian Engineering College Trivandrum", tier: 3 },
  { name: "Jyothi Engineering College Thrissur", tier: 3 },
  { name: "Guru Nanak Dev Engineering College", tier: 3 },
  { name: "Maharishi Markandeshwar University", tier: 3 },
  { name: "Kurukshetra University", tier: 3 },
  { name: "Manav Rachna International Institute", tier: 3 },
  { name: "Amity University Haryana", tier: 3 },
  { name: "Assam Engineering College", tier: 3 },
  { name: "Tezpur University", tier: 3 },
  { name: "Gauhati University", tier: 3 },
  { name: "Don Bosco University Guwahati", tier: 3 },
  { name: "Sikkim Manipal Institute of Technology", tier: 3 },
  { name: "DIT University Dehradun", tier: 3 },
  { name: "Uttaranchal University", tier: 3 },
  { name: "Quantum University Roorkee", tier: 3 },
  { name: "ITER Bhubaneswar", tier: 3 },
  { name: "Trident Academy of Technology", tier: 3 },
  { name: "Veer Surendra Sai University of Technology", tier: 3 },
  { name: "Gandhi Institute of Engineering and Technology", tier: 3 },
  { name: "BIT Sindri", tier: 3 },
  { name: "Muzaffarpur Institute of Technology", tier: 3 },
  { name: "Gaya College of Engineering", tier: 3 },
  { name: "Goa College of Engineering", tier: 3 },
  { name: "Don Bosco College of Engineering Goa", tier: 3 },
  { name: "NIT Jaipur", tier: 2 },
  { name: "NIT Nagpur", tier: 2 },
  { name: "IIIT Manipur", tier: 2 },
  { name: "COEP Pune", tier: 2 },
  { name: "BIT Mesra", tier: 2 },
  { name: "MSRIT Bangalore", tier: 2 },
  { name: "Motilal Nehru National Institute of Technology", tier: 2 },
  { name: "Maulana Azad National Institute of Technology", tier: 2 },
  { name: "Dr. B.R. Ambedkar NIT Jalandhar", tier: 2 },
  { name: "International Institute of Information Technology Naya Raipur", tier: 2 },
  { name: "Ashoka University", tier: 2 },
  { name: "Azim Premji University", tier: 2 },
  { name: "Flame University Pune", tier: 2 },
  { name: "Pune University", tier: 3 },
  { name: "Mumbai University", tier: 3 },
  { name: "Osmania University", tier: 3 },
  { name: "VIT Chennai", tier: 3 },
  { name: "VIT Bhopal", tier: 3 },
  { name: "VIT AP", tier: 3 },
  { name: "Symbiosis Institute of Technology", tier: 3 },
  { name: "Nirma University", tier: 3 },
  { name: "SRM Kattankulathur", tier: 3 },
  { name: "Kalinga Institute of Industrial Technology", tier: 3 },
  { name: "Fr. Conceicao Rodrigues College of Engineering", tier: 3 },
  { name: "Vidyalankar Institute of Technology", tier: 3 },
  { name: "Saveetha Engineering College", tier: 3 },
  { name: "Koneru Lakshmaiah Education Foundation", tier: 3 },
  { name: "Vivekananda Institute of Professional Studies", tier: 3 },
  { name: "Malaviya National Institute of Technology Jaipur", tier: 3 },
  { name: "MNIT Jaipur", tier: 3 },
  { name: "Sardar Patel University", tier: 3 },
  { name: "Gujarat Technological University", tier: 3 },
  { name: "Indus University Ahmedabad", tier: 3 },
  { name: "Silver Oak College of Engineering", tier: 3 },
  { name: "Rajkiya Engineering College Kannauj", tier: 3 },
  { name: "Oriental Institute of Science and Technology", tier: 3 },
  { name: "Truba Institute of Engineering", tier: 3 },
  { name: "Punjabi University Patiala", tier: 3 },
  { name: "YMCA University of Science and Technology", tier: 3 },
  { name: "Deenbandhu Chhotu Ram University", tier: 3 },
  { name: "RCC Institute of Information Technology", tier: 3 },
  { name: "Centurion University of Technology", tier: 3 },
  { name: "APJ Abdul Kalam Technological University", tier: 3 },
  { name: "Jorhat Engineering College", tier: 3 },
  { name: "Dibrugarh University", tier: 3 },
  { name: "National Institute of Technology Meghalaya", tier: 3 },
  { name: "Manipur Institute of Technology", tier: 3 },
  { name: "Tripura Institute of Technology", tier: 3 },
  { name: "Mizoram University", tier: 3 },
  { name: "Nagaland University", tier: 3 },
  { name: "Himachal Pradesh University", tier: 3 },
  { name: "Jaypee University Solan", tier: 3 },
  { name: "University of Jammu", tier: 3 },
  { name: "Baba Ghulam Shah Badshah University", tier: 3 },
  { name: "Central University of Rajasthan", tier: 3 },
  { name: "Pondicherry Engineering College", tier: 3 },
  { name: "Ramaiah Institute of Technology", tier: 3 },
  { name: "Periyar University", tier: 3 },
  { name: "Amrita School of Engineering Chennai", tier: 3 },
  { name: "Jerusalem College of Engineering", tier: 3 },
  { name: "Misrimal Navajee Munoth Jain Engineering College", tier: 3 },
  { name: "Priyadarshini College of Engineering Nagpur", tier: 3 },
  { name: "Sipna College of Engineering Amravati", tier: 3 },
  { name: "Indira College of Engineering Pune", tier: 3 },
  { name: "Zeal College of Engineering Pune", tier: 3 },
  { name: "NBN Sinhgad School of Engineering", tier: 3 },
  { name: "MAEER MIT College Aurangabad", tier: 3 },
  { name: "Deogiri Institute of Engineering Aurangabad", tier: 3 },
  { name: "Amity University Lucknow", tier: 3 },
  { name: "Babu Banarasi Das University", tier: 3 },
  { name: "Invertis University Bareilly", tier: 3 },
  { name: "Teerthanker Mahaveer University", tier: 3 },
  { name: "GLA University Mathura", tier: 3 },
  { name: "Sharda University Greater Noida", tier: 3 },
  { name: "Raj Kumar Goel Institute of Technology", tier: 3 },
  { name: "IMS Engineering College Ghaziabad", tier: 3 },
  { name: "Kiet Group of Institutions Ghaziabad", tier: 3 },
  { name: "Ajay Kumar Garg Engineering College", tier: 3 },
  { name: "Hindustan College of Science and Technology", tier: 3 },
  { name: "Krishna Engineering College Ghaziabad", tier: 3 },
  { name: "Inderprastha Engineering College", tier: 3 },
  { name: "Moradabad Institute of Technology", tier: 3 },
  { name: "Bundelkhand University Jhansi", tier: 3 },
  { name: "Rajasthan Technical University", tier: 3 },
  { name: "Suresh Gyan Vihar University", tier: 3 },
  { name: "Amity University Jaipur", tier: 3 },
  { name: "Pacific University Udaipur", tier: 3 },
  { name: "Bikaner Technical University", tier: 3 },
  { name: "Government Engineering College Bikaner", tier: 3 },
  { name: "RK University Rajkot", tier: 3 },
  { name: "Atmiya University Rajkot", tier: 3 },
  { name: "Sankalchand Patel University", tier: 3 },
  { name: "Nirma Institute of Technology", tier: 3 },
  { name: "Rajiv Gandhi Proudyogiki Vishwavidyalaya", tier: 3 },
  { name: "Sagar Institute of Research and Technology", tier: 3 },
  { name: "Technocrats Institute of Technology Bhopal", tier: 3 },
  { name: "Radharaman Institute of Technology", tier: 3 },
  { name: "IES College of Technology Bhopal", tier: 3 },
  { name: "Columbia Institute of Engineering Raipur", tier: 3 },
  { name: "Shri Shankaracharya Technical Campus", tier: 3 },
  { name: "Chhattisgarh Swami Vivekanand Technical University", tier: 3 },
  { name: "Jalpaiguri Government Engineering College", tier: 3 },
  { name: "Murshidabad College of Engineering", tier: 3 },
  { name: "Cooch Behar Government Engineering College", tier: 3 },
  { name: "Bankura Unnayani Institute of Engineering", tier: 3 },
  { name: "Birbhum Institute of Engineering", tier: 3 },
  { name: "Hooghly Engineering and Technology College", tier: 3 },
  { name: "Siliguri Institute of Technology", tier: 3 },
  { name: "Future Institute of Engineering Kolkata", tier: 3 },
  { name: "National Institute of Foundry and Forge Technology", tier: 3 },
  { name: "Ranchi University", tier: 3 },
  { name: "Vinoba Bhave University", tier: 3 },
  { name: "Patna University", tier: 3 },
  { name: "Darbhanga College of Engineering", tier: 3 },
  { name: "Sitamarhi Institute of Technology", tier: 3 },
  { name: "Supaul College of Engineering", tier: 3 },
  { name: "IIIT Bhubaneswar", tier: 3 },
  { name: "Parala Maharaja Engineering College", tier: 3 },
  { name: "College of Engineering Bhubaneswar", tier: 3 },
  { name: "Indus College of Engineering Odisha", tier: 3 },
  { name: "Koustuv Institute of Self Domain", tier: 3 },
  { name: "Raajdhani Engineering College", tier: 3 },
  { name: "Sree Chitra Thirunal College of Engineering", tier: 3 },
  { name: "Ilahia College of Engineering", tier: 3 },
  { name: "Toc H Institute of Science and Technology", tier: 3 },
  { name: "Sahrdaya College of Engineering", tier: 3 },
  { name: "Viswajyothi College of Engineering", tier: 3 },
  { name: "Sree Narayana Gurukulam College of Engineering", tier: 3 },
  { name: "Lourdes Matha College of Science and Technology", tier: 3 },
  { name: "Baselios Mathews II College of Engineering", tier: 3 },
  { name: "J.C. Bose University of Science and Technology", tier: 3 },
  { name: "Lingayas Vidyapeeth Faridabad", tier: 3 },
  { name: "PDM University Bahadurgarh", tier: 3 },
  { name: "Geeta Institute of Management and Technology", tier: 3 },
  { name: "Lovely Professional University Phagwara", tier: 3 },
  { name: "Rayat Bahra University", tier: 3 },
  { name: "Swami Vivekanand College of Engineering", tier: 3 },
  { name: "CT Institute of Engineering Jalandhar", tier: 3 },
  { name: "Graphic Era University Dehradun", tier: 3 },
  { name: "Invertis University Dehradun", tier: 3 },
  { name: "Himgiri Zee University", tier: 3 },
  { name: "Baddi University", tier: 3 },
  { name: "APG Shimla University", tier: 3 },
  { name: "Eternal University Baru Sahib", tier: 3 },
  { name: "Arni University Kangra", tier: 3 },
  { name: "Bodoland University", tier: 3 },
  { name: "Kaziranga University", tier: 3 },
  { name: "Royal Global University Guwahati", tier: 3 },
  { name: "Assam Down Town University", tier: 3 },
  { name: "Sikkim University", tier: 3 },
  { name: "ICFAI University Tripura", tier: 3 },
  { name: "Arunachal University of Studies", tier: 3 },
  { name: "JSS Academy of Technical Education Noida", tier: 3 },
  { name: "Vidya Vikas Institute of Engineering Mysore", tier: 3 },
  { name: "Vivekananda College of Engineering Puttur", tier: 3 },
  { name: "Sri Taralabalu Jagadguru Institute of Technology Ranebennur", tier: 3 },
  { name: "KLE Dr MS Sheshgiri College of Engineering Belgaum", tier: 3 },
  { name: "Jain College of Engineering Belgaum", tier: 3 },
  { name: "KLE Technological University Hubli", tier: 3 },
  { name: "Proudhadevaraya Institute of Technology Hospet", tier: 3 },
  { name: "Sri Venkateshwara College of Engineering Bangalore", tier: 3 },
  { name: "Bangalore College of Engineering and Technology", tier: 3 },
  { name: "Proudhadevaraya Institute of Technology Bangalore", tier: 3 },
  { name: "Akshaya Institute of Technology Tumkur", tier: 3 },
  { name: "Bapuji Institute of Engineering Shimoga", tier: 3 },
  { name: "Vidyavardhaka College of Engineering Bangalore", tier: 3 },
  { name: "Dayananda Sagar Academy of Technology Bangalore", tier: 3 },
  { name: "Acharya NRV School of Architecture Bangalore", tier: 3 },
  { name: "Hassan Institute of Medical Sciences", tier: 3 },
  { name: "Jawaharlal Nehru College of Engineering Shivamogga", tier: 3 },
  { name: "Maharaja Institute of Technology Talkad", tier: 3 },
  { name: "Mangalore University", tier: 3 },
  { name: "Mysore University", tier: 3 },
  { name: "Poornaprajna Institute of Management Udupi", tier: 3 },
  { name: "Rao Bahadur Y Mahabaleswarappa Engineering College Bellary", tier: 3 },
  { name: "Sri Dharmasthala Manjunatheshwara College of Engineering Dharwad", tier: 3 },
  { name: "Sri Revana Siddeshwara Institute of Technology Bangalore", tier: 3 },
  { name: "Surana College of Engineering Bangalore", tier: 3 },
  { name: "The Oxford College of Engineering Bangalore", tier: 3 },
  { name: "Tumkur University", tier: 3 },
  { name: "Welingkar Institute of Management Bangalore", tier: 3 },
  { name: "Acharya Institutes Bangalore", tier: 3 },
  { name: "BMS Evening College of Engineering Bangalore", tier: 3 },
  { name: "Bangalore Institute of Technology Bangalore", tier: 3 },
  { name: "Cauvery College of Engineering Mysore", tier: 3 },
  { name: "Coorg Institute of Technology Ponnampet", tier: 3 },
  { name: "HKBK College of Engineering Bangalore", tier: 3 },
  { name: "Hubballi Institute of Technology", tier: 3 },
  { name: "KLE Society Polytechnic Belgaum", tier: 3 },
  { name: "Moodlakatte Institute of Technology Kundapura", tier: 3 },
  { name: "Nagarjuna College of Engineering Bangalore", tier: 3 },
  { name: "Nitte Meenakshi Institute of Technology Bangalore", tier: 3 },
  { name: "Raja Rajeshwari College of Engineering Bangalore", tier: 3 },
  { name: "S J M Institute of Technology Chitradurga", tier: 3 },
  { name: "Shri Pillappa College of Engineering Bangalore", tier: 3 },
  { name: "Shridevi Institute of Engineering and Technology Tumkur", tier: 3 },
  { name: "Smt Kamala and Sri Venkappa M Agadi College of Engineering Gadag", tier: 3 },
  { name: "Sri Siddhartha Academy of Higher Education Tumkur", tier: 3 },
  { name: "Srinivas College of Engineering Mangalore", tier: 3 },
  { name: "Tatyasaheb Kore Institute of Engineering Warananagar", tier: 3 },
  { name: "Veerappa Nisty Engineering College Shorapur", tier: 3 },
  { name: "Visvesvaraya Technological University Belagavi", tier: 3 },
  { name: "Viveka Institute of Technology Puttur", tier: 3 },
  { name: "Yenepoya Institute of Technology Moodbidri", tier: 3 },
  { name: "New Horizon College of Engineering Bangalore", tier: 3 },
  { name: "Presidency College of Engineering Bangalore", tier: 3 },
  { name: "Jyothy Institute of Technology Bangalore", tier: 3 },
  { name: "Bangalore North University", tier: 3 },
  { name: "Seshadripuram College Bangalore", tier: 3 },
  { name: "Reva Institute of Technology Bangalore", tier: 3 },
  { name: "Nagarjuna College of Engineering and Technology Bangalore", tier: 3 },
  { name: "Shirdi Sai Engineering College Bangalore", tier: 3 },
  { name: "Shree Devi Institute of Technology Mangalore", tier: 3 },
  { name: "Siddharth Institute of Engineering Bangalore", tier: 3 },
  { name: "Silicon City College Bangalore", tier: 3 },
  { name: "Sindhi Institute of Management Bangalore", tier: 3 },
  { name: "Sir MVIT Bangalore", tier: 3 },
  { name: "Bharath Institute of Engineering Tumkur", tier: 3 },
  { name: "Sapthagiri College of Engineering Tumkur", tier: 3 },
  { name: "Vidyavardhaka College of Engineering Tumkur", tier: 3 },
  { name: "Vivekananda Institute of Technology Tumkur", tier: 3 },
  { name: "Yellamma Dasappa Institute of Technology Tumkur", tier: 3 },
  { name: "Sri Venkateshwara College of Engineering Kolar", tier: 3 },
  { name: "Vivekananda Institute of Technology Kolar", tier: 3 },
  { name: "Srinivasa Institute of Technology Kolar", tier: 3 },
  { name: "Navodaya Institute of Technology Kolar", tier: 3 },
  { name: "Sapthagiri Institute of Technology Kolar", tier: 3 },
  { name: "Presidency Institute of Engineering Kolar", tier: 3 },
  { name: "Sri Jayachamarajendra Polytechnic Mandya", tier: 3 },
  { name: "Vidyavardhaka Sangha Polytechnic Mandya", tier: 3 },
  { name: "Vivekananda Institute of Technology Mandya", tier: 3 },
  { name: "Sapthagiri College of Engineering Mandya", tier: 3 },
  { name: "Nagarjuna College of Engineering Mandya", tier: 3 },
  { name: "Sri Siddhartha Institute of Technology Mandya", tier: 3 },
  { name: "Channabasaveshwara Institute of Technology Mandya", tier: 3 },
  { name: "Lourdes College Mangalore", tier: 3 },
  { name: "St Aloysius College Mangalore", tier: 3 },
  { name: "Milagres College Mangalore", tier: 3 },
  { name: "Acharya Institute of Technology Bangalore", tier: 3 },
  { name: "Aditya College of Engineering Bangalore", tier: 3 },
  { name: "AIT Bangalore", tier: 3 },
  { name: "Akshaya Institute of Technology Bangalore", tier: 3 },
  { name: "Alliance College of Engineering Bangalore", tier: 3 },
  { name: "Alpha College of Engineering Bangalore", tier: 3 },
  { name: "Amruta Institute of Engineering Bangalore", tier: 3 },
  { name: "Anekal College of Engineering Bangalore", tier: 3 },
  { name: "Anjuman Institute of Technology Bhatkal", tier: 3 },
  { name: "Annasaheb Dange College of Engineering Ashta", tier: 3 },
  { name: "Atria Institute of Technology Bangalore", tier: 3 },
  { name: "Aziz Sait Institute of Engineering Bangalore", tier: 3 },
  { name: "Bangalore College of Engineering and Technology Bangalore", tier: 3 },
  { name: "Bangalore Technological Institute Bangalore", tier: 3 },
  { name: "Bharath Institute of Engineering Bangalore", tier: 3 },
  { name: "BMS College of Engineering Bangalore", tier: 2 },
  { name: "Cambridge Institute of Technology North Campus Bangalore", tier: 3 },
  { name: "Canara Engineering College Bangalore", tier: 3 },
  { name: "Carmel Polytechnic College Bangalore", tier: 3 },
  { name: "Christ College of Engineering Bangalore", tier: 3 },
  { name: "CMR College of Engineering and Technology Bangalore", tier: 3 },
  { name: "CMR Institute of Technology Bangalore", tier: 3 },
  { name: "CMR University Bangalore", tier: 3 },
  { name: "Dayananda Sagar College of Engineering Bangalore", tier: 3 },
  { name: "Dayananda Sagar University Bangalore", tier: 3 },
  { name: "East West Institute of Technology Bangalore", tier: 3 },
  { name: "Francis Xavier Engineering College Bangalore", tier: 3 },
  { name: "Global Academy of Technology Bangalore", tier: 3 },
  { name: "Gopalan College of Engineering Bangalore", tier: 3 },
  { name: "Guru Nanak Dev Engineering College Bangalore", tier: 3 },
  { name: "Impact College of Engineering Bangalore", tier: 3 },
  { name: "Indian Academy Degree College Bangalore", tier: 3 },
  { name: "Indira Gandhi Institute of Technology Bangalore", tier: 3 },
  { name: "Jain College of Engineering Bangalore", tier: 3 },
  { name: "Jnana Vikas Institute of Technology Bangalore", tier: 3 },
  { name: "JSS Academy of Technical Education Bangalore", tier: 3 },
  { name: "K S School of Engineering and Management Bangalore", tier: 3 },
  { name: "Kammavari Sangham Institute of Technology Bangalore", tier: 3 },
  { name: "Khaja Bandanawaz College of Engineering Bangalore", tier: 3 },
  { name: "KNS Institute of Technology Bangalore", tier: 3 },
  { name: "Maharaja Institute of Technology Bangalore", tier: 3 },
  { name: "Mangalore Institute of Technology Bangalore", tier: 3 },
  { name: "Moodlakatte Institute of Technology Bangalore", tier: 3 },
  { name: "Reva University Bangalore", tier: 3 },
  { name: "RV College of Engineering Bangalore", tier: 2 },
  { name: "RV Institute of Technology Bangalore", tier: 3 },
  { name: "Sastra University Bangalore", tier: 3 },
  { name: "Sir M Visvesvaraya Institute of Technology Bangalore", tier: 3 },
  { name: "Bangalore North University Bangalore", tier: 3 },
  { name: "Presidency Institute of Engineering Bangalore", tier: 3 },
  { name: "Sri Siddhartha Institute of Technology Bangalore", tier: 3 },
  { name: "Acharya and BM Reddy College of Pharmacy Bangalore", tier: 3 },
  { name: "Adichunchanagiri Institute of Technology Bangalore", tier: 3 },
  { name: "Aditya Institute of Technology Bangalore", tier: 3 },
  { name: "Agni College of Technology Bangalore", tier: 3 },
  { name: "Ahalia School of Engineering Bangalore", tier: 3 },
  { name: "Akshaya Institute of Technology North Bangalore", tier: 3 },
  { name: "Alva College of Engineering Bangalore", tier: 3 },
  { name: "Amruta College of Engineering Bangalore", tier: 3 },
  { name: "Anekal Engineering College Bangalore", tier: 3 },
  { name: "Anjuman Engineering College Bangalore", tier: 3 },
  { name: "Annasaheb Engineering College Bangalore", tier: 3 },
  { name: "Apex Institute of Technology Bangalore", tier: 3 },
  { name: "Aravali College of Engineering Bangalore", tier: 3 },
  { name: "Arcot Sri Mahalakshmi Women Engineering College Bangalore", tier: 3 },
  { name: "Arjun College of Technology Bangalore", tier: 3 },
  { name: "Arya Institute of Engineering Bangalore", tier: 3 },
  { name: "Ashraya Institute of Computer Science Bangalore", tier: 3 },
  { name: "Atria College of Engineering Bangalore", tier: 3 },
  { name: "Aziz Sait Institute of Technology Bangalore", tier: 3 },
  { name: "Bapuji Institute of Engineering Bangalore", tier: 3 },
  { name: "Basaveshwar Engineering College Bangalore", tier: 3 },
  { name: "Bearys Institute of Technology Bangalore", tier: 3 },
  { name: "Bhagwan Mahavir Jain College Bangalore", tier: 3 },
  { name: "Bharatesh Education Trust Global Engineering College Bangalore", tier: 3 },
  { name: "Bhoomi College of Engineering Bangalore", tier: 3 },
  { name: "Bhuvaneshwari College of Engineering Bangalore", tier: 3 },
  { name: "Canara College of Engineering Bangalore", tier: 3 },
  { name: "Capital Institute of Technology Bangalore", tier: 3 },
  { name: "Cauvery Institute of Technology Bangalore", tier: 3 },
  { name: "Channabasaveshwara Institute of Technology Bangalore", tier: 3 },
  { name: "Chetan Business School Bangalore", tier: 3 },
  { name: "Chitkara University Bangalore", tier: 3 },
  { name: "Coorg Institute of Technology Bangalore", tier: 3 },
  { name: "Dayananda Sagar Business School Bangalore", tier: 3 },
  { name: "Deccan College of Engineering Bangalore", tier: 3 },
  { name: "Deeksha Center for Learning Bangalore", tier: 3 },
  { name: "Dhruva College of Management Bangalore", tier: 3 },
  { name: "Disha Institute of Management Bangalore", tier: 3 },
  { name: "Divya Jyothi College of Engineering Bangalore", tier: 3 },
  { name: "Dr Ambedkar College of Engineering Bangalore", tier: 3 },
  { name: "Dr CNS Institute of Technology Bangalore", tier: 3 },
  { name: "Dr Kariappa College of Engineering Bangalore", tier: 3 },
  { name: "Dr MGR Educational and Research Institute Bangalore", tier: 3 },
  { name: "East West College of Engineering Bangalore", tier: 3 },
  { name: "Ekalavya Institute of Technology Bangalore", tier: 3 },
  { name: "Eklavya College of Engineering Bangalore", tier: 3 },
  { name: "Farooqia College of Engineering Bangalore", tier: 3 },
  { name: "Ganga Institute of Technology Bangalore", tier: 3 },
  { name: "Ghousia College of Engineering Bangalore", tier: 3 },
  { name: "Global Institute of Engineering Bangalore", tier: 3 },
  { name: "Gopalan Institute of Technology Bangalore", tier: 3 },
  { name: "Government Tool Room and Training Centre Bangalore", tier: 3 },
  { name: "Grace College of Engineering Bangalore", tier: 3 },
  { name: "Guru Nanak Institute of Technology Bangalore", tier: 3 },
  { name: "Gurunanak Dev Engineering College Bangalore", tier: 3 },
  { name: "Hillside College of Engineering Bangalore", tier: 3 },
  { name: "Hindustan Institute of Engineering Technology Bangalore", tier: 3 },
  { name: "Indira Gandhi Memorial Institute of Technology Bangalore", tier: 3 },
  { name: "Indus Business Academy Bangalore", tier: 3 },
  { name: "Indus College of Engineering Bangalore", tier: 3 },
  { name: "Innovative Institute of Technology Bangalore", tier: 3 },
  { name: "Institute of Engineering and Technology Bangalore", tier: 3 },
  { name: "International Institute of Engineering Bangalore", tier: 3 },
  { name: "Jain Institute of Technology Bangalore", tier: 3 },
  { name: "Janatha Shikshana Samithi Institute of Technology Bangalore", tier: 3 },
  { name: "Jawaharlal Nehru College of Engineering Bangalore", tier: 3 },
  { name: "Jnana Bharathi Institute of Technology Bangalore", tier: 3 },
  { name: "Jnana Deepa Vidyapeeth Bangalore", tier: 3 },
  { name: "Jnana Ganga Institute of Technology Bangalore", tier: 3 },
  { name: "Jnana Jyothi Institute of Technology Bangalore", tier: 3 },
  { name: "Jnana Prabodhini Institute of Technology Bangalore", tier: 3 },
  { name: "Jnana Saraswathi Institute of Technology Bangalore", tier: 3 },
  { name: "Jnana Sindhu Institute of Technology Bangalore", tier: 3 },
  { name: "Jnana Vikas College of Engineering Bangalore", tier: 3 },
  { name: "Jnana Yoga Institute of Technology Bangalore", tier: 3 },
  { name: "Kalyani Institute of Technology Bangalore", tier: 3 },
  { name: "Kammavari Sangham College of Engineering Bangalore", tier: 3 },
  { name: "Kempegowda Institute of Medical Sciences Bangalore", tier: 3 },
  { name: "Kengeri Institute of Technology Bangalore", tier: 3 },
  { name: "Khaja Bandanawaz Institute of Technology Bangalore", tier: 3 },
  { name: "Koshys Institute of Management Studies Bangalore", tier: 3 },
  { name: "Kumaran Institute of Technology Bangalore", tier: 3 },
  { name: "Lal Bahadur Shastri Institute of Technology Bangalore", tier: 3 },
  { name: "Lingarajappa College of Engineering Bangalore", tier: 3 },
  { name: "Lotus Institute of Engineering Bangalore", tier: 3 },
  { name: "Mahatma Gandhi Institute of Technology Bangalore", tier: 3 },
  { name: "Malnad Institute of Technology Bangalore", tier: 3 },
  { name: "Mangala Institute of Technology Bangalore", tier: 3 },
  { name: "Manipal Institute of Technology Bangalore", tier: 3 },
  { name: "Matha Institute of Technology Bangalore", tier: 3 },
  { name: "Moodlakatte Institute of Technology North Bangalore", tier: 3 },
  { name: "Mount Carmel College Bangalore", tier: 3 },
  { name: "Mysore Institute of Technology Bangalore", tier: 3 },
  { name: "Nagarjuna Institute of Technology Bangalore", tier: 3 },
  { name: "Nandi Institute of Technology Bangalore", tier: 3 },
  { name: "National Institute of Engineering Bangalore", tier: 3 },
  { name: "Navkis College of Engineering Bangalore", tier: 3 },
  { name: "Nehru Institute of Engineering Bangalore", tier: 3 },
  { name: "Nitte Institute of Technology Bangalore", tier: 3 },
  { name: "Nrupathunga University Bangalore", tier: 3 },
  { name: "PA College of Engineering Bangalore", tier: 3 },
  { name: "Padmashree Institute of Management Bangalore", tier: 3 },
  { name: "Poornaprajna College of Engineering Bangalore", tier: 3 },
  { name: "Prajwal College of Engineering Bangalore", tier: 3 },
  { name: "Presidency College Bangalore", tier: 3 },
  { name: "Raja Rajeshwari Medical College Bangalore", tier: 3 },
  { name: "Rajiv Gandhi Institute of Technology Bangalore", tier: 3 },
  { name: "Ramaiah University of Applied Sciences Bangalore", tier: 3 },
  { name: "Rao Bahadur Y Mahabaleswarappa Engineering College Bangalore", tier: 3 },
  { name: "Rooman Technologies Bangalore", tier: 3 },
  { name: "Sahyadri College of Engineering Bangalore", tier: 3 },
  { name: "Sarada Vilas College of Engineering Bangalore", tier: 3 },
  { name: "Saraswathi Institute of Technology Bangalore", tier: 3 },
  { name: "Sardar Patel Institute of Technology Bangalore", tier: 3 },
  { name: "Sathyabama Institute of Science Bangalore", tier: 3 },
  { name: "Seshadripuram Institute of Management Studies Bangalore", tier: 3 },
  { name: "Shree Devi Institute of Technology Bangalore", tier: 3 },
  { name: "Shri Dharmasthala Manjunatheshwara College Bangalore", tier: 3 },
  { name: "Shri Venkateshwara University Bangalore", tier: 3 },
  { name: "Siddaganga Institute of Technology Bangalore", tier: 3 },
  { name: "Srinivasa Institute of Technology Bangalore", tier: 3 },
  { name: "St Francis De Sales College Bangalore", tier: 3 },
  { name: "St Johns Medical College Bangalore", tier: 3 },
  { name: "St Joseph College of Engineering Bangalore", tier: 3 },
  { name: "St Peters Engineering College Bangalore", tier: 3 },
  { name: "Swamy Vivekananda Engineering College Bangalore", tier: 3 },
  { name: "Symbiosis Institute of Technology Bangalore", tier: 3 },
  { name: "Tatyasaheb Kore Institute of Engineering Bangalore", tier: 3 },
  { name: "Tontadarya College of Engineering Bangalore", tier: 3 },
  { name: "Tumkur Institute of Technology Bangalore", tier: 3 },
];
window.tierInfo = {
  1: {
    label: "Tier 1 - Top Institute",
    desc: "Top-tier institution. You have access to the best opportunities. Most top tech companies actively recruit from your campus.",
    color: "tier1",
    companies: ["Google", "Microsoft", "Amazon", "Meta", "Apple", "Goldman Sachs", "McKinsey", "DE Shaw"]
  },
  2: {
    label: "Tier 2 - Strong Institute",
    desc: "Strong institution. Many good companies recruit from your campus. With strong skills, top companies are also reachable.",
    color: "tier2",
    companies: ["Amazon", "Microsoft", "Flipkart", "Walmart", "Adobe", "Salesforce", "Uber", "Swiggy"]
  },
  3: {
    label: "Tier 3 - Average Institute",
    desc: "Average institution. Focus on building strong skills and projects. Mid-tier companies actively hire from your campus.",
    color: "tier3",
    companies: ["Infosys", "TCS", "Wipro", "Cognizant", "Capgemini", "HCL", "Tech Mahindra"]
  },
  4: {
    label: "Tier 4 - Other Institute",
    desc: "Lesser-known institution. Build strong skills, certifications, and projects to stand out.",
    color: "tier4",
    companies: ["Infosys", "TCS", "Wipro", "Cognizant", "Mphasis", "Hexaware"]
  }
};

window.companies = [
  {
    name: "Google", badge: "Mostly Tier 1", badgeClass: "t1",
    t1: 80, t2: 15, t3: 5, t4: 0,
    roles: [
      { role: "SDE", tier: "Tier 1 Only" },
      { role: "Data Analyst", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Microsoft", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 65, t2: 30, t3: 5, t4: 0,
    roles: [
      { role: "SDE", tier: "Tier 1 & 2" },
      { role: "PM", tier: "Tier 1 Only" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Amazon", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 60, t2: 35, t3: 5, t4: 0,
    roles: [
      { role: "SDE", tier: "Tier 1 & 2" },
      { role: "Operations", tier: "Tier 2 & 3" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Flipkart", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 55, t2: 40, t3: 5, t4: 0,
    roles: [
      { role: "SDE", tier: "Tier 1 & 2" },
      { role: "Data Scientist", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 2 & 3" }
    ]
  },
  {
    name: "Infosys", badge: "Open for All", badgeClass: "t3",
    t1: 20, t2: 35, t3: 30, t4: 15,
    roles: [
      { role: "Systems Engineer", tier: "All Tiers" },
      { role: "Senior SDE", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "All Tiers" }
    ]
  },
  {
    name: "TCS", badge: "Open for All", badgeClass: "t3",
    t1: 15, t2: 30, t3: 35, t4: 20,
    roles: [
      { role: "Assistant Systems Engineer", tier: "All Tiers" },
      { role: "Digital", tier: "Tier 2 & 3" },
      { role: "Ninja", tier: "All Tiers" }
    ]
  },
  {
    name: "Wipro", badge: "Open for All", badgeClass: "t3",
    t1: 10, t2: 25, t3: 40, t4: 25,
    roles: [
      { role: "Project Engineer", tier: "All Tiers" },
      { role: "Elite", tier: "Tier 2 & 3" },
      { role: "Intern", tier: "All Tiers" }
    ]
  },
  {
    name: "Adobe", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 60, t2: 35, t3: 5, t4: 0,
    roles: [
      { role: "SDE", tier: "Tier 1 & 2" },
      { role: "UX Designer", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Apple", badge: "Mostly Tier 1", badgeClass: "t1",
    t1: 75, t2: 20, t3: 5, t4: 0,
    roles: [
      { role: "Hardware Engineer", tier: "Tier 1 Only" },
      { role: "SDE", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Meta (Facebook)", badge: "Mostly Tier 1", badgeClass: "t1",
    t1: 85, t2: 10, t3: 5, t4: 0,
    roles: [
      { role: "SDE", tier: "Tier 1 Only" },
      { role: "Data Engineer", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "IBM", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 50, t2: 40, t3: 10, t4: 0,
    roles: [
      { role: "Systems Engineer", tier: "Tier 1 & 2" },
      { role: "Developer", tier: "Tier 2 & 3" },
      { role: "Intern", tier: "All Tiers" }
    ]
  },
  {
    name: "Intel", badge: "Mostly Tier 1", badgeClass: "t1",
    t1: 70, t2: 25, t3: 5, t4: 0,
    roles: [
      { role: "Hardware Design", tier: "Tier 1 Only" },
      { role: "SDE", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Accenture", badge: "Open for All", badgeClass: "t3",
    t1: 25, t2: 40, t3: 25, t4: 10,
    roles: [
      { role: "Associate", tier: "All Tiers" },
      { role: "Senior Associate", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "All Tiers" }
    ]
  },
  {
    name: "Deloitte", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 55, t2: 35, t3: 10, t4: 0,
    roles: [
      { role: "Consultant", tier: "Tier 1 & 2" },
      { role: "Analyst", tier: "All Tiers" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Goldman Sachs", badge: "Mostly Tier 1", badgeClass: "t1",
    t1: 90, t2: 8, t3: 2, t4: 0,
    roles: [
      { role: "Analyst", tier: "Tier 1 Only" },
      { role: "Software Developer", tier: "Tier 1 Only" },
      { role: "Intern", tier: "Tier 1 Only" }
    ]
  },
  {
    name: "Morgan Stanley", badge: "Mostly Tier 1", badgeClass: "t1",
    t1: 85, t2: 12, t3: 3, t4: 0,
    roles: [
      { role: "Analyst", tier: "Tier 1 Only" },
      { role: "Tech Analyst", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 1 Only" }
    ]
  },
  {
    name: "Citibank", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 60, t2: 35, t3: 5, t4: 0,
    roles: [
      { role: "Technology Analyst", tier: "Tier 1 & 2" },
      { role: "Operations", tier: "All Tiers" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "HDFC Bank", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 50, t2: 45, t3: 5, t4: 0,
    roles: [
      { role: "Technology Graduate", tier: "Tier 1 & 2" },
      { role: "Operations", tier: "All Tiers" },
      { role: "Analyst", tier: "Tier 2 & 3" }
    ]
  },
  {
    name: "ICICI Bank", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 48, t2: 42, t3: 10, t4: 0,
    roles: [
      { role: "Technology Officer", tier: "Tier 1 & 2" },
      { role: "Credit Analyst", tier: "All Tiers" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Axis Bank", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 45, t2: 45, t3: 10, t4: 0,
    roles: [
      { role: "Management Trainee", tier: "Tier 1 & 2" },
      { role: "Operations", tier: "All Tiers" },
      { role: "Analyst", tier: "Tier 2 & 3" }
    ]
  },
  {
    name: "Swiggy", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 65, t2: 30, t3: 5, t4: 0,
    roles: [
      { role: "SDE", tier: "Tier 1 & 2" },
      { role: "Data Analyst", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "OYO Rooms", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 60, t2: 35, t3: 5, t4: 0,
    roles: [
      { role: "SDE", tier: "Tier 1 & 2" },
      { role: "Product Manager", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Uber", badge: "Mostly Tier 1", badgeClass: "t1",
    t1: 78, t2: 18, t3: 4, t4: 0,
    roles: [
      { role: "SDE", tier: "Tier 1 & 2" },
      { role: "Data Scientist", tier: "Tier 1 Only" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Airbnb", badge: "Mostly Tier 1", badgeClass: "t1",
    t1: 80, t2: 15, t3: 5, t4: 0,
    roles: [
      { role: "SDE", tier: "Tier 1 Only" },
      { role: "Design", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Netflix", badge: "Mostly Tier 1", badgeClass: "t1",
    t1: 82, t2: 14, t3: 4, t4: 0,
    roles: [
      { role: "SDE", tier: "Tier 1 Only" },
      { role: "DevOps Engineer", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 1 Only" }
    ]
  },
  {
    name: "Spotify", badge: "Mostly Tier 1", badgeClass: "t1",
    t1: 75, t2: 20, t3: 5, t4: 0,
    roles: [
      { role: "SDE", tier: "Tier 1 & 2" },
      { role: "Data Engineer", tier: "Tier 1 Only" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Tesla", badge: "Mostly Tier 1", badgeClass: "t1",
    t1: 88, t2: 10, t3: 2, t4: 0,
    roles: [
      { role: "Software Engineer", tier: "Tier 1 Only" },
      { role: "Firmware Engineer", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Nvidia", badge: "Mostly Tier 1", badgeClass: "t1",
    t1: 85, t2: 12, t3: 3, t4: 0,
    roles: [
      { role: "GPU Software Engineer", tier: "Tier 1 Only" },
      { role: "System Software Engineer", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "ARM Holdings", badge: "Mostly Tier 1", badgeClass: "t1",
    t1: 80, t2: 16, t3: 4, t4: 0,
    roles: [
      { role: "Design Engineer", tier: "Tier 1 Only" },
      { role: "Software Engineer", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Dell EMC", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 55, t2: 38, t3: 7, t4: 0,
    roles: [
      { role: "SDE", tier: "Tier 1 & 2" },
      { role: "Systems Engineer", tier: "Tier 2 & 3" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "HP (Hewlett Packard)", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 50, t2: 42, t3: 8, t4: 0,
    roles: [
      { role: "Software Developer", tier: "Tier 1 & 2" },
      { role: "Systems Administrator", tier: "All Tiers" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Cisco", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 60, t2: 35, t3: 5, t4: 0,
    roles: [
      { role: "Network Engineer", tier: "Tier 1 & 2" },
      { role: "Software Engineer", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "VMware", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 65, t2: 30, t3: 5, t4: 0,
    roles: [
      { role: "SDE", tier: "Tier 1 & 2" },
      { role: "DevOps Engineer", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Salesforce", badge: "Mostly Tier 1", badgeClass: "t1",
    t1: 72, t2: 22, t3: 6, t4: 0,
    roles: [
      { role: "SDE", tier: "Tier 1 & 2" },
      { role: "Cloud Engineer", tier: "Tier 1 Only" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Oracle", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 58, t2: 36, t3: 6, t4: 0,
    roles: [
      { role: "Database Administrator", tier: "Tier 1 & 2" },
      { role: "SDE", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "SAP", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 55, t2: 38, t3: 7, t4: 0,
    roles: [
      { role: "Software Engineer", tier: "Tier 1 & 2" },
      { role: "Support Engineer", tier: "All Tiers" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "L&T (Larsen & Toubro)", badge: "Open for All", badgeClass: "t3",
    t1: 30, t2: 40, t3: 20, t4: 10,
    roles: [
      { role: "Graduate Engineer", tier: "All Tiers" },
      { role: "Senior Engineer", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "All Tiers" }
    ]
  },
  {
    name: "Siemens", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 52, t2: 40, t3: 8, t4: 0,
    roles: [
      { role: "Software Engineer", tier: "Tier 1 & 2" },
      { role: "Control Systems Engineer", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "All Tiers" }
    ]
  },
  {
    name: "General Electric (GE)", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 50, t2: 42, t3: 8, t4: 0,
    roles: [
      { role: "Digital Engineer", tier: "Tier 1 & 2" },
      { role: "Manufacturing Engineer", tier: "Tier 2 & 3" },
      { role: "Intern", tier: "All Tiers" }
    ]
  },
  {
    name: "BHEL (Bharat Heavy Electricals)", badge: "Open for All", badgeClass: "t3",
    t1: 20, t2: 35, t3: 30, t4: 15,
    roles: [
      { role: "Graduate Engineer Trainee", tier: "All Tiers" },
      { role: "Senior Engineer", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "All Tiers" }
    ]
  },
  {
    name: "Maruti Suzuki", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 45, t2: 45, t3: 10, t4: 0,
    roles: [
      { role: "Graduate Engineer", tier: "Tier 1 & 2" },
      { role: "Manufacturing Engineer", tier: "All Tiers" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Hyundai Motors", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 48, t2: 42, t3: 10, t4: 0,
    roles: [
      { role: "Software Engineer", tier: "Tier 1 & 2" },
      { role: "Controls Engineer", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "All Tiers" }
    ]
  },
  {
    name: "Bosch", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 58, t2: 35, t3: 7, t4: 0,
    roles: [
      { role: "Software Engineer", tier: "Tier 1 & 2" },
      { role: "Electronics Engineer", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "BMW", badge: "Mostly Tier 1", badgeClass: "t1",
    t1: 70, t2: 25, t3: 5, t4: 0,
    roles: [
      { role: "Software Developer", tier: "Tier 1 & 2" },
      { role: "Electronics Design Engineer", tier: "Tier 1 Only" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Qualcomm", badge: "Mostly Tier 1", badgeClass: "t1",
    t1: 82, t2: 14, t3: 4, t4: 0,
    roles: [
      { role: "Design Engineer", tier: "Tier 1 Only" },
      { role: "Software Engineer", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Texas Instruments", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 68, t2: 28, t3: 4, t4: 0,
    roles: [
      { role: "Design Engineer", tier: "Tier 1 & 2" },
      { role: "Software Engineer", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "Broadcom", badge: "Mostly Tier 1", badgeClass: "t1",
    t1: 76, t2: 20, t3: 4, t4: 0,
    roles: [
      { role: "Hardware Design Engineer", tier: "Tier 1 Only" },
      { role: "Software Engineer", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "Tier 1 & 2" }
    ]
  },
  {
    name: "HCL Technologies", badge: "Tier 1 & 2", badgeClass: "t2",
    t1: 40, t2: 45, t3: 15, t4: 0,
    roles: [
      { role: "Systems Engineer", tier: "All Tiers" },
      { role: "SDE", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "All Tiers" }
    ]
  },
  {
    name: "Tech Mahindra", badge: "Open for All", badgeClass: "t3",
    t1: 18, t2: 32, t3: 35, t4: 15,
    roles: [
      { role: "Engineer", tier: "All Tiers" },
      { role: "Senior Developer", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "All Tiers" }
    ]
  },
  {
    name: "Cognizant", badge: "Open for All", badgeClass: "t3",
    t1: 22, t2: 38, t3: 30, t4: 10,
    roles: [
      { role: "Associate", tier: "All Tiers" },
      { role: "Senior Developer", tier: "Tier 1 & 2" },
      { role: "Intern", tier: "All Tiers" }
    ]
  },
  { name: "Capgemini", badge: "Open for All", badgeClass: "t3", t1: 20, t2: 35, t3: 32, t4: 13, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Mphasis", badge: "Open for All", badgeClass: "t3", t1: 18, t2: 32, t3: 35, t4: 15, roles: [{ role: "Software Engineer", tier: "All Tiers" }, { role: "Lead", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Hexaware", badge: "Open for All", badgeClass: "t3", t1: 17, t2: 30, t3: 37, t4: 16, roles: [{ role: "Developer", tier: "All Tiers" }, { role: "Senior Developer", tier: "Tier 2 & 3" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "NCS (Nippon Code Solutions)", badge: "Open for All", badgeClass: "t3", t1: 16, t2: 28, t3: 38, t4: 18, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Zensar", badge: "Open for All", badgeClass: "t3", t1: 19, t2: 34, t3: 33, t4: 14, roles: [{ role: "Software Engineer", tier: "All Tiers" }, { role: "Tech Lead", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Cerner", badge: "Open for All", badgeClass: "t3", t1: 21, t2: 36, t3: 31, t4: 12, roles: [{ role: "Healthcare IT", tier: "All Tiers" }, { role: "Analyst", tier: "All Tiers" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Mindtree", badge: "Open for All", badgeClass: "t3", t1: 25, t2: 40, t3: 28, t4: 7, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Genpact", badge: "Open for All", badgeClass: "t3", t1: 15, t2: 28, t3: 40, t4: 17, roles: [{ role: "Process Associate", tier: "All Tiers" }, { role: "Analyst", tier: "All Tiers" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Sutherland", badge: "Open for All", badgeClass: "t3", t1: 12, t2: 25, t3: 43, t4: 20, roles: [{ role: "Operations", tier: "All Tiers" }, { role: "Team Lead", tier: "Tier 2 & 3" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Conduent", badge: "Open for All", badgeClass: "t3", t1: 14, t2: 26, t3: 42, t4: 18, roles: [{ role: "BPO Executive", tier: "All Tiers" }, { role: "Senior Executive", tier: "Tier 2 & 3" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "ATOS", badge: "Open for All", badgeClass: "t3", t1: 23, t2: 37, t3: 30, t4: 10, roles: [{ role: "Consultant", tier: "All Tiers" }, { role: "Senior Consultant", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "EY (Ernst & Young)", badge: "Open for All", badgeClass: "t3", t1: 28, t2: 42, t3: 22, t4: 8, roles: [{ role: "Consultant", tier: "All Tiers" }, { role: "Senior Consultant", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "PwC", badge: "Open for All", badgeClass: "t3", t1: 29, t2: 43, t3: 21, t4: 7, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "KPMG", badge: "Open for All", badgeClass: "t3", t1: 27, t2: 41, t3: 24, t4: 8, roles: [{ role: "Associate Consultant", tier: "All Tiers" }, { role: "Senior", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "BNY Mellon", badge: "Open for All", badgeClass: "t3", t1: 26, t2: 39, t3: 26, t4: 9, roles: [{ role: "Analyst", tier: "All Tiers" }, { role: "Senior Analyst", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Carrier", badge: "Open for All", badgeClass: "t3", t1: 15, t2: 30, t3: 40, t4: 15, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Whirlpool", badge: "Open for All", badgeClass: "t3", t1: 18, t2: 32, t3: 36, t4: 14, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Mahindra & Mahindra", badge: "Open for All", badgeClass: "t3", t1: 20, t2: 35, t3: 33, t4: 12, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Bajaj Auto", badge: "Open for All", badgeClass: "t3", t1: 17, t2: 31, t3: 38, t4: 14, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Hero MotoCorp", badge: "Open for All", badgeClass: "t3", t1: 16, t2: 29, t3: 40, t4: 15, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "TVS Motor", badge: "Open for All", badgeClass: "t3", t1: 15, t2: 28, t3: 41, t4: 16, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Tata Motors", badge: "Open for All", badgeClass: "t3", t1: 22, t2: 37, t3: 30, t4: 11, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Ashok Leyland", badge: "Open for All", badgeClass: "t3", t1: 14, t2: 27, t3: 42, t4: 17, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Daimler", badge: "Open for All", badgeClass: "t3", t1: 24, t2: 39, t3: 28, t4: 9, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Volkswagen", badge: "Open for All", badgeClass: "t3", t1: 25, t2: 40, t3: 27, t4: 8, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Reliance Industries", badge: "Open for All", badgeClass: "t3", t1: 26, t2: 41, t3: 25, t4: 8, roles: [{ role: "Graduate Trainee", tier: "All Tiers" }, { role: "Senior Trainee", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Oil and Natural Gas Corporation (ONGC)", badge: "Open for All", badgeClass: "t3", t1: 24, t2: 38, t3: 29, t4: 9, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Indian Oil", badge: "Open for All", badgeClass: "t3", t1: 23, t2: 37, t3: 30, t4: 10, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Hindustan Petroleum", badge: "Open for All", badgeClass: "t3", t1: 21, t2: 35, t3: 32, t4: 12, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Bharat Petroleum", badge: "Open for All", badgeClass: "t3", t1: 20, t2: 34, t3: 33, t4: 13, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Coal India", badge: "Open for All", badgeClass: "t3", t1: 18, t2: 32, t3: 36, t4: 14, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Power Finance Corporation (PFC)", badge: "Open for All", badgeClass: "t3", t1: 22, t2: 36, t3: 31, t4: 11, roles: [{ role: "Officer", tier: "All Tiers" }, { role: "Senior Officer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "REC (Rural Electrification Corporation)", badge: "Open for All", badgeClass: "t3", t1: 21, t2: 35, t3: 32, t4: 12, roles: [{ role: "Officer", tier: "All Tiers" }, { role: "Senior Officer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "NTPC", badge: "Open for All", badgeClass: "t3", t1: 23, t2: 37, t3: 30, t4: 10, roles: [{ role: "Graduate Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Airtel", badge: "Open for All", badgeClass: "t3", t1: 20, t2: 34, t3: 33, t4: 13, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Jio (Reliance Jio)", badge: "Open for All", badgeClass: "t3", t1: 22, t2: 36, t3: 31, t4: 11, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Vodafone Idea", badge: "Open for All", badgeClass: "t3", t1: 18, t2: 31, t3: 36, t4: 15, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "BSNL", badge: "Open for All", badgeClass: "t3", t1: 17, t2: 30, t3: 38, t4: 15, roles: [{ role: "JTO", tier: "All Tiers" }, { role: "SDE", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Snapdeal", badge: "Open for All", badgeClass: "t3", t1: 19, t2: 33, t3: 34, t4: 14, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Amazon India", badge: "Open for All", badgeClass: "t3", t1: 24, t2: 39, t3: 28, t4: 9, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Grofers", badge: "Open for All", badgeClass: "t3", t1: 17, t2: 31, t3: 37, t4: 15, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Urban Company", badge: "Open for All", badgeClass: "t3", t1: 16, t2: 29, t3: 40, t4: 15, roles: [{ role: "Executive", tier: "All Tiers" }, { role: "Senior Executive", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "PharmEasy", badge: "Open for All", badgeClass: "t3", t1: 18, t2: 32, t3: 36, t4: 14, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Zomato", badge: "Open for All", badgeClass: "t3", t1: 21, t2: 35, t3: 32, t4: 12, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "PayTM", badge: "Open for All", badgeClass: "t3", t1: 20, t2: 34, t3: 33, t4: 13, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Ola", badge: "Open for All", badgeClass: "t3", t1: 22, t2: 37, t3: 30, t4: 11, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Unacademy", badge: "Open for All", badgeClass: "t3", t1: 19, t2: 33, t3: 34, t4: 14, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Vedanta", badge: "Open for All", badgeClass: "t3", t1: 21, t2: 35, t3: 32, t4: 12, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Hindalco", badge: "Open for All", badgeClass: "t3", t1: 19, t2: 33, t3: 34, t4: 14, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "SAIL (Steel Authority)", badge: "Open for All", badgeClass: "t3", t1: 20, t2: 34, t3: 33, t4: 13, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Jindal Steel", badge: "Open for All", badgeClass: "t3", t1: 18, t2: 32, t3: 36, t4: 14, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Essar Steel", badge: "Open for All", badgeClass: "t3", t1: 17, t2: 30, t3: 38, t4: 15, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Cement Corporation of India", badge: "Open for All", badgeClass: "t3", t1: 16, t2: 28, t3: 40, t4: 16, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "ACC Cement", badge: "Open for All", badgeClass: "t3", t1: 19, t2: 33, t3: 34, t4: 14, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Ambuja Cement", badge: "Open for All", badgeClass: "t3", t1: 20, t2: 34, t3: 33, t4: 13, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "UltraTech Cement", badge: "Open for All", badgeClass: "t3", t1: 21, t2: 35, t3: 32, t4: 12, roles: [{ role: "Engineer", tier: "All Tiers" }, { role: "Senior Engineer", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Asian Paints", badge: "Open for All", badgeClass: "t3", t1: 22, t2: 37, t3: 30, t4: 11, roles: [{ role: "Executive", tier: "All Tiers" }, { role: "Senior Executive", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Berger Paints", badge: "Open for All", badgeClass: "t3", t1: 18, t2: 32, t3: 36, t4: 14, roles: [{ role: "Executive", tier: "All Tiers" }, { role: "Senior Executive", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Britannia Industries", badge: "Open for All", badgeClass: "t3", t1: 20, t2: 34, t3: 33, t4: 13, roles: [{ role: "Executive", tier: "All Tiers" }, { role: "Senior Executive", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "ITC Limited", badge: "Open for All", badgeClass: "t3", t1: 23, t2: 38, t3: 29, t4: 10, roles: [{ role: "Executive", tier: "All Tiers" }, { role: "Senior Executive", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Nestlé India", badge: "Open for All", badgeClass: "t3", t1: 24, t2: 39, t3: 28, t4: 9, roles: [{ role: "Executive", tier: "All Tiers" }, { role: "Senior Executive", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Hindustan Unilever", badge: "Open for All", badgeClass: "t3", t1: 25, t2: 40, t3: 27, t4: 8, roles: [{ role: "Executive", tier: "All Tiers" }, { role: "Senior Executive", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Procter & Gamble", badge: "Open for All", badgeClass: "t3", t1: 26, t2: 41, t3: 26, t4: 7, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Colgate-Palmolive", badge: "Open for All", badgeClass: "t3", t1: 21, t2: 35, t3: 32, t4: 12, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Godrej Industries", badge: "Open for All", badgeClass: "t3", t1: 20, t2: 34, t3: 33, t4: 13, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Marico", badge: "Open for All", badgeClass: "t3", t1: 19, t2: 33, t3: 34, t4: 14, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Dabur India", badge: "Open for All", badgeClass: "t3", t1: 18, t2: 32, t3: 36, t4: 14, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Ajinomoto", badge: "Open for All", badgeClass: "t3", t1: 17, t2: 30, t3: 38, t4: 15, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Mondelez India", badge: "Open for All", badgeClass: "t3", t1: 20, t2: 34, t3: 33, t4: 13, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "United Breweries", badge: "Open for All", badgeClass: "t3", t1: 19, t2: 33, t3: 34, t4: 14, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Sula Wines", badge: "Open for All", badgeClass: "t3", t1: 16, t2: 28, t3: 40, t4: 16, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Diageo India", badge: "Open for All", badgeClass: "t3", t1: 21, t2: 35, t3: 32, t4: 12, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "DLF", badge: "Open for All", badgeClass: "t3", t1: 20, t2: 34, t3: 33, t4: 13, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Lodha", badge: "Open for All", badgeClass: "t3", t1: 19, t2: 33, t3: 34, t4: 14, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Prestige Group", badge: "Open for All", badgeClass: "t3", t1: 18, t2: 32, t3: 36, t4: 14, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Oberoi Group", badge: "Open for All", badgeClass: "t3", t1: 22, t2: 37, t3: 30, t4: 11, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Taj Hotels", badge: "Open for All", badgeClass: "t3", t1: 21, t2: 35, t3: 32, t4: 12, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "ITC Hotels", badge: "Open for All", badgeClass: "t3", t1: 20, t2: 34, t3: 33, t4: 13, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Club Mahindra", badge: "Open for All", badgeClass: "t3", t1: 19, t2: 33, t3: 34, t4: 14, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Cox & Kings", badge: "Open for All", badgeClass: "t3", t1: 17, t2: 30, t3: 38, t4: 15, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Thomas Cook India", badge: "Open for All", badgeClass: "t3", t1: 18, t2: 32, t3: 36, t4: 14, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "MakeMyTrip", badge: "Open for All", badgeClass: "t3", t1: 20, t2: 34, t3: 33, t4: 13, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Goibibo", badge: "Open for All", badgeClass: "t3", t1: 16, t2: 29, t3: 40, t4: 15, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Irctc", badge: "Open for All", badgeClass: "t3", t1: 21, t2: 35, t3: 32, t4: 12, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Indian Railways", badge: "Open for All", badgeClass: "t3", t1: 23, t2: 38, t3: 29, t4: 10, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Airports Authority of India", badge: "Open for All", badgeClass: "t3", t1: 22, t2: 37, t3: 30, t4: 11, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Port Authority", badge: "Open for All", badgeClass: "t3", t1: 20, t2: 34, t3: 33, t4: 13, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Shipping Corporation of India", badge: "Open for All", badgeClass: "t3", t1: 19, t2: 33, t3: 34, t4: 14, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "FedEx", badge: "Open for All", badgeClass: "t3", t1: 21, t2: 35, t3: 32, t4: 12, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "DHL", badge: "Open for All", badgeClass: "t3", t1: 20, t2: 34, t3: 33, t4: 13, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "DTDC", badge: "Open for All", badgeClass: "t3", t1: 17, t2: 31, t3: 37, t4: 15, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "First Flight Couriers", badge: "Open for All", badgeClass: "t3", t1: 16, t2: 29, t3: 40, t4: 15, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Blue Dart", badge: "Open for All", badgeClass: "t3", t1: 19, t2: 33, t3: 34, t4: 14, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Allcargo", badge: "Open for All", badgeClass: "t3", t1: 18, t2: 32, t3: 36, t4: 14, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "MESCO", badge: "Open for All", badgeClass: "t3", t1: 15, t2: 27, t3: 41, t4: 17, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Kerala Shipping", badge: "Open for All", badgeClass: "t3", t1: 16, t2: 28, t3: 40, t4: 16, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Max Healthcare", badge: "Open for All", badgeClass: "t3", t1: 20, t2: 34, t3: 33, t4: 13, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Apollo Hospitals", badge: "Open for All", badgeClass: "t3", t1: 22, t2: 37, t3: 30, t4: 11, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Fortis Healthcare", badge: "Open for All", badgeClass: "t3", t1: 21, t2: 35, t3: 32, t4: 12, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Dr. Reddy's Labs", badge: "Open for All", badgeClass: "t3", t1: 23, t2: 38, t3: 29, t4: 10, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Cipla", badge: "Open for All", badgeClass: "t3", t1: 22, t2: 37, t3: 30, t4: 11, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Sun Pharma", badge: "Open for All", badgeClass: "t3", t1: 21, t2: 35, t3: 32, t4: 12, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Lupin", badge: "Open for All", badgeClass: "t3", t1: 20, t2: 34, t3: 33, t4: 13, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Aurobindo Pharma", badge: "Open for All", badgeClass: "t3", t1: 19, t2: 33, t3: 34, t4: 14, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Mylan", badge: "Open for All", badgeClass: "t3", t1: 18, t2: 32, t3: 36, t4: 14, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Torrent Pharma", badge: "Open for All", badgeClass: "t3", t1: 17, t2: 30, t3: 38, t4: 15, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] },
  { name: "Biocon", badge: "Open for All", badgeClass: "t3", t1: 24, t2: 39, t3: 28, t4: 9, roles: [{ role: "Associate", tier: "All Tiers" }, { role: "Senior Associate", tier: "Tier 1 & 2" }, { role: "Intern", tier: "All Tiers" }] }
];

window.jobs = [
  { company: "Google", role: "Software Engineer", location: "Bangalore", tier: "T1", worth: "yes" },
  { company: "Microsoft", role: "SDE II", location: "Hyderabad", tier: "T1 & T2", worth: "yes" },
  { company: "Amazon", role: "SDE I", location: "Bangalore", tier: "T1 & T2", worth: "yes" },
  { company: "Flipkart", role: "Data Scientist", location: "Bangalore", tier: "T1 & T2", worth: "maybe" },
  { company: "Infosys", role: "Systems Engineer", location: "Pune", tier: "All Tiers", worth: "yes" },
  { company: "TCS", role: "Assistant Systems Engineer", location: "Chennai", tier: "All Tiers", worth: "yes" },
  { company: "Adobe", role: "UX Designer", location: "Noida", tier: "T1 & T2", worth: "maybe" },
  { company: "Wipro", role: "Project Engineer", location: "Bangalore", tier: "All Tiers", worth: "yes" },
  { company: "Goldman Sachs", role: "Analyst", location: "Bangalore", tier: "T1 Only", worth: "no" },
  { company: "Meta", role: "SDE", location: "Remote", tier: "T1 Only", worth: "no" }
];
